### ISSUE TITLE
HACS Support

### ISSUE THREAD

**Issue by aneisch** [thomasloven/lovelace-toggle-lock-entity-row#12]
Can you please modify the repo to be complaint with requirements for HACS store listing?

https://hacs.netlify.com/developer/general/

**Comment by thomasloven** [comment]
https://hacs.netlify.com/usage/settings/#add-custom-repositories

**Comment by aneisch** [comment]
I have done this. I opened the issue so that you may expose your wonderful plugin to a wider audience by default. 

Thanks for your hard work and for the great plugin!

**Comment by thomasloven** [comment]
I'm slowly adding my plugins to HACS as I'm in the process of updating them all.
Thank you!
