### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by dolenec** [thomasloven/lovelace-toggle-lock-entity-row#15]
Can you manage so that this component would be implemented into HACS update system?

Some links:
https://community.home-assistant.io/t/custom-component-hacs/121727

https://hacs.netlify.com/docs/developer/start

**Comment by thomasloven** [comment]
Some more links:
https://community.home-assistant.io/t/custom-component-hacs/121727/53
https://hacs.xyz/ (watch the gif)
