### ISSUE TITLE
please don't deprecate

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-toggle-lock-entity-row#17]
Having used your card for some time now, the ease of config is much appreciated. The restriction-card you suggest we use from here on might be way more powerful, but is far more complex to configure also. 

Moreover, it is not very clear if this can also lock a single entity, as the restriction-card needs a card, not an entity.

All in all, please don't deprecate this card?
thanks for considering

**Comment by thomasloven** [comment]
Maybe you should take a look at the readme? Specifically the example for how to use it with a single entity?

**Comment by Mariusthvdb** [comment]
Not sure why you presume I haven’t read the  readme... the restriction card can show the lock on a row using the extra required row: option, but it isn’t an entity lock (like your card), it’s a row lock. As per Ian’s own words.

I’ve got it showing the lock alright, but, as mentioned in my post above, it requires many extra settings ( eg in themes for the lock to show on the toggle) for it to become a true replacement for the ease of your card.

Right out of the box with defaults the lock is hardly visible ( color, size) and needs a lot of attention.

Yours was (is) set and go.

My request still stands ... ;-)

**Comment by thomasloven** [comment]
I won't remove this from github. It will still be there, but I have no interest in maintaining it, keep up with changes in Home Assistant, fix bugs, tweak designs or add features etc. when there's another plugin that does the same thing and more - better - with two more lines of set-once configuration.
