### ISSUE TITLE
toggle-lock-entity-row pin entry has a option request

### ISSUE THREAD

**Issue by vMeph** [thomasloven/lovelace-toggle-lock-entity-row#9]
would like to thank you for the awesome lovelace LL card that  lovelace-toggle-lock-entity-row is .
this card is perfect to give you some protection in some devices that you dont want to touch buttons by mistake, unless you realy need, so i was wondering if there is any way toggle-lock-entity-row could have option for pin mode entry protection, that would give even more protection from not letting some users to use that button...

**Comment by thomasloven** [comment]
This row is now deprecated. Please use [restriction-card](https://github.com/iantrich/restriction-card) instead.
